### ISSUE TITLE
Throwing a loaded Arquebus crashes the game

### ISSUE THREAD

**Issue by meganukebmp** [Zarkonnen/VSRangedWeapons#1]
```
Running on 64 bit Windows with 8 GB RAM 
Version: v1.14.10 (Stable)22.5.2021 г. 3:21:01: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at RangedWeapons.ItemRangedWeapon.checkStillLoaded(ItemSlot slot, EntityAgent interactingEntity)
   at RangedWeapons.ItemRangedWeapon.<>c__DisplayClass13_0.<RegisterCheckStillLoadedCallback>b__0(Single dt)
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world)
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt)
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime)
   at _vKnDSS3ZW5fZhqcIJSzL9xbAUttA._mhcyOBzdAWALla9FVcjc15WACGi(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._3HP2xkrryy8Ktr1q1yqHHv9s1kb(Single )
   at _w1hCRzQiukKlSxBw6hggDUXQ0jC._JbXJA0SA6LQOS6diuqtXAjMb8Fo(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _ISiSTzGmXXpAqo3PzdxdVD1bClZ._ofvn0Tr1zNGCbNV3SxvKs2MXNP(_C7CLMRbe3BejVtaARYCgl7Bg1vl , String[] )
   at _0Y0SN1uu1V65pRLxvnN2xsIjXAg._ofvn0Tr1zNGCbNV3SxvKs2MXNP(ThreadStart )
```

Likely unhandled unloading event

**Comment by Zarkonnen** [comment]
Thanks for the report. Yeah, that's it trying to figure out if it's still loaded, and assuming that it's still being held. Can probably fix it.

**Comment by Zarkonnen** [comment]
This is fixed now AFAIK.
