### ISSUE TITLE
client crash with blowgun use

### ISSUE THREAD

**Issue by prestonhashworth** [Zarkonnen/VSRangedWeapons#10]
Environment: server is running in Linux, v1.19.8 

Log output:
Running on 64 bit Windows 10.0.22631.0 with 81803 MB RAM
Game Version: v1.19.8 (Stable)
9/18/2024 5:07:51 PM: Critical error occurred in the following mod: RangedWeapons@0.6.2
Loaded Mods: balancedthirst@0.0.41, bettertraders@0.0.7, compass2@3.0.0, entitiesinteract@1.0.11, fantasycreatures@0.7.1, caninae@1.0.16, casuariidae@1.0.8, machairodontinae@1.0.9, pantherinae@1.1.9, rhinocerotidae@1.0.3, sirenia@1.0.5, millwright@1.1.7, primitivesurvival@3.6.5, RangedWeapons@0.6.2, rnroutlawsvillagerscompat@1.3.1, rustandrot@0.0.6, swordz@1.1.8, locustmod2@2.4.2, game@1.19.8, wildcrafttrees@1.2.4, zoombuttonreborn@1.8.0, additionalmolds@1.0.1, ancienttools@1.5.18, betterruins@0.3.7, carryon@1.7.4, commonlib@2.5.0-rc.2, medievalexpansion@3.13.1, meteoricexpansion@1.2.5, outlawmod@1.2.3, petai@2.2.6, prospecttogether@1.3.0, rivers@3.1.0, rustboundmagic@1.9.74, sailboat@1.3.1, spawnersapi@1.0.8, creative@1.19.8, vsimgui@1.1.5, vsquest@1.2.0, survival@1.19.8, vsvillage@1.0.6, wgmt@1.0.1, cats@2.0.3, configlib@1.3.13, feverstonewilds@1.5.0-rc.2, OutlawMeat@0.0.2, playercorpse@1.10.1-rc.1, vsvillageviking@1.0.0, vsvillageaged@0.0.4, vsvillageindustrial@0.0.4, vsvillagetowers@0.0.4
System.MissingFieldException: Field not found: 'Vintagestory.API.Common.Entities.Entity.AnimManager'.
   at RangedWeapons.ItemRangedWeapon.OnHeldInteractStart(ItemSlot slot, EntityAgent interactingEntity, BlockSelection blockSel, EntitySelection entitySel, Boolean firstEvent, EnumHandHandling& handling)
   at Vintagestory.API.Common.CollectibleObject.OnHeldUseStart(ItemSlot slot, EntityAgent byEntity, BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, Boolean firstEvent, EnumHandHandling& handling) in VintagestoryApi\Common\Collectible\Collectible.cs:line 1106
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.TryBeginUseActiveSlotItem(BlockSelection blockSel, EntitySelection entitySel, EnumHandInteract useType, EnumHandHandling& handling) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 831
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 386
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 89
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 186
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 809
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1013
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 676
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 651
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 88
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 324
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by Zarkonnen** [comment]
Yeah, I'm sorry, I noped out of maintaining this mod due to it constantly breaking due to API changes. I didn't realize I was signing up for a long-term maintenance job when I made it.
